server:
  port: 8081
spring:
  application:
    name: voting-ms
  data:
    mongodb:
      uri: mongodb+srv://yaakermi:uMOhzWo3hutWNHMW@voting-sys.a2zkg.mongodb.net/?retryWrites=true&w=majority&appName=voting-sys
      database: votingdb
logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG  # Logs MongoDB queries and operations
          database: INFO  # Change 'votingdb' to a valid log level like 'INFO'




voting-ms:
  message: "Welcome to Vote service related local APIs"
  contactDetails:
    name: "Akermi yahia - Engineer"
    email: "ya.akermi@esi-sba.dz"
  onCallSupport:
    - (213) 540-752-251
    - (213) 661-161-378
